import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DiffService, DiffEntityResult } from '../types/diff';
import { DataGroup } from '../types/dataGroup';
import { CacheManager } from '../../cache-manager/cache-manager.service';
import { DataGroupConfig } from '../../cache-manager/interfaces/cache-config.interface';

@Injectable()
export class CacheDiffService extends DiffService {
  private readonly logger = new Logger(CacheDiffService.name);

  constructor(
    private readonly cacheManager: CacheManager<any>,
    private readonly configService: ConfigService,
  ) {
    super();
  }

  async getDiff(
    squadronIds: string[],
    startDate: string,
    endDate: string,
    dataGroup?: DataGroup,
    entityVersions?: Record<string, Record<string, number>>,
  ): Promise<DiffEntityResult[]> {
    if (!dataGroup) {
      this.logger.warn('No dataGroup provided to CacheDiffService');
      return [];
    }

    const dataGroupMappings = this.configService.get<Record<string, DataGroupConfig[]>>('cache.dataGroupMapping');

    if (!dataGroupMappings?.[dataGroup]) {
      this.logger.warn(`No DataGroupConfig found for dataGroup: ${dataGroup}`);
      return [];
    }

    const entityConfigs = dataGroupMappings[dataGroup];
    const days = this.getDaysArray(startDate, endDate);
    const diffResults: DiffEntityResult[] = (await Promise.all(
      entityConfigs.map(async (config) => {
        const entities = await this.cacheManager.acquire(config.entityName, days, dataGroup, config.fields, { squadronIds });

        return Promise.all(entities
          .filter(entity => !entity.squadronId || squadronIds.includes(entity.squadronId))
          .map(async (entity) => {
            const currentVersion = entity.version || 1;
            const clientVersion = entityVersions?.[config.entityName]?.[entity.id];

            if (clientVersion === undefined || currentVersion > clientVersion) {
              const resolvedData = await this.resolveNestedPointers(entity, days, new Set<string>());
              return {
                entityName: config.entityName,
                entityId: entity.id,
                version: currentVersion,
                data: resolvedData,
              };
            }
            return null;
          }));
      })
    )).flat().filter(res => res !== null) as DiffEntityResult[];

    return diffResults;
  }

  public getDaysArray(startDateString: string, endDateString: string): string[] {
    const days: string[] = [];
    const start = new Date(startDateString);
    const end = new Date(endDateString);

    if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || start > end) {
      return [];
    }

    // Normalize to midnight UTC to avoid daylight saving issues during iteration
    start.setUTCHours(0, 0, 0, 0);
    end.setUTCHours(0, 0, 0, 0);

    const current = new Date(start);
    while (current <= end) {
      const yyyy = current.getUTCFullYear();
      const mm = String(current.getUTCMonth() + 1).padStart(2, '0');
      const dd = String(current.getUTCDate()).padStart(2, '0');
      days.push(`${yyyy}-${mm}-${dd}`);
      current.setUTCDate(current.getUTCDate() + 1);
    }

    return days;
  }

  /**
   * Recursively traverses the entity object. When it encounters a generic pointer signature 
   * `{ __typename, id }` generated by the GraphQLDataSource, it performs a cache lookup 
   * and replaces the pointer with the fully resolved object, deeply nesting the result.
   */
  public async resolveNestedPointers(entity: any, days: string[], visitedIds: Set<string>): Promise<any> {
    if (!entity || typeof entity !== 'object') {
      return entity;
    }

    // Detect structural pointer: exactly __typename and id (and nothing else)
    const keys = Object.keys(entity);
    if (entity.__typename && entity.id && keys.length === 2) {
      const pointerId = `${entity.__typename}:${entity.id}`;

      if (visitedIds.has(pointerId)) {
        return entity; // Break circular dependency loops
      }
      visitedIds.add(pointerId);

      // Perform a lightweight lookup without registering a dataGroup dependency
      const resolvedList = await this.cacheManager.acquire(entity.__typename, days);
      const resolvedEntity = resolvedList.find((e: any) => e.id === entity.id);

      if (resolvedEntity) {
        // Recursively resolve the newly attached child
        const cloned = { ...resolvedEntity };
        for (const key of Object.keys(cloned)) {
          cloned[key] = await this.resolveNestedPointers(cloned[key], days, visitedIds);
        }
        return cloned;
      }

      // Fallback: If cache miss, leave the pointer intact
      return entity;
    }

    if (Array.isArray(entity)) {
      return Promise.all(entity.map(item => this.resolveNestedPointers(item, days, visitedIds)));
    }

    // Traverse regular entity fields
    const result: any = { ...entity };
    for (const key of Object.keys(result)) {
      result[key] = await this.resolveNestedPointers(result[key], days, visitedIds);
    }

    return result;
  }
}
